### ISSUE TITLE
Support client side absolute url anchor tags

### ISSUE THREAD

**Issue by timlind** [zygo-io/zygo#1]
The following should cause navigation client side:

```
<a href="/two">Two</a>
```

**Comment by Bubblyworld** [comment]
Added this feature in the [latest commit](https://github.com/Bubblyworld/Zygo/commit/ef17cc27f505b96e35e084a25f1d4109aa2f4000). If the base href of the <a> tag matches that of the router then it delegates the navigation the router, otherwise it just lets it do its thing,
